trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  displayName: 'Descargar codigo fuente de GastroHotel'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
  displayName: 'Configurar entorno Python'

- script: |
    cd backend
    pip install -r requirements.txt
    pip install pytest "httpx<0.28.0"
  displayName: 'Instalar librerias y dependencias del servidor'

- script: |
    cd backend
    pytest test_api.py
  displayName: 'Ejecutar pruebas automatizadas de FastAPI'
